# Generated by Django 5.2.1 on 2025-06-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("developer", models.CharField(max_length=20)),
                ("bio", models.TextField(max_length=255)),
                ("release_year", models.DateTimeField(null=True)),
                ("is_rented", models.BooleanField(default=False)),
                ("amount", models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
