# Generated by Django 5.2.1 on 2025-06-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_game_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="amount",
        ),
        migrations.AddField(
            model_name="game",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
