# Generated by Django 5.2.1 on 2025-06-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_game_amount_game_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="developer",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
    ]
