# Generated by Django 5.2.1 on 2025-06-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_game_developer_alter_game_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
    ]
